language: objective-c
osx_image: xcode9
before_script:
    - gem install fastlane
    - gem install xcov
    - gem install danger-xcov
    - gem update
script:
    - fastlane test
cache:
    carthage: true
branches:
    only:
        - master
        - develop
